// Writes TRANSLATIONS_REVIEW.md: every translated string side by side (FR | EN | ES)
// so a human can proofread them. Run: npm run translations
import { readFileSync, writeFileSync } from 'node:fs';

const read = (path) => JSON.parse(readFileSync(new URL(`../${path}`, import.meta.url), 'utf8'));
const langs = ['fr', 'en', 'es'];
const dicts = Object.fromEntries(langs.map((l) => [l, read(`src/i18n/${l}.json`)]));

// Flatten nested keys: { a: { b: 'x' } } → { 'a.b': 'x' }
function flatten(obj, prefix = '', out = {}) {
  for (const [key, value] of Object.entries(obj)) {
    const path = prefix ? `${prefix}.${key}` : key;
    if (value && typeof value === 'object') flatten(value, path, out);
    else out[path] = String(value);
  }
  return out;
}

const cell = (text = '') => text.replace(/\|/g, '\\|').replace(/\n/g, ' ');
const rows = [];
const flat = Object.fromEntries(langs.map((l) => [l, flatten(dicts[l])]));
for (const key of Object.keys(flat.fr)) {
  const values = langs.map((l) => flat[l][key]);
  // Skip strings that are identical everywhere on purpose (proper nouns, codes).
  if (values.every((v) => v === values[0]) && !key.startsWith('about.')) continue;
  rows.push(`| \`${key}\` | ${values.map(cell).join(' | ')} |`);
}

const achievements = read('src/data/achievements.json').items;
const achievementRows = achievements.flatMap((item) =>
  ['dateLabel', 'title', 'place']
    .filter((field) => item[field])
    .map((field) => `| \`${item.id}.${field}\`${item.template ? ' *(template)*' : ''} | ${langs.map((l) => cell(item[field][l])).join(' | ')} |`),
);

const gallery = read('src/data/gallery.json').items;
const galleryRows = gallery.map((item) => `| \`${item.image}.alt\` | ${langs.map((l) => cell(item.alt[l])).join(' | ')} |`);

const header = '| Key | Français | English | Español |\n|---|---|---|---|';
const doc = `# Translations to review

Generated by \`npm run translations\` from \`src/i18n/*.json\`, \`src/data/achievements.json\` and \`src/data/gallery.json\`.
Song titles, event names and proper nouns are intentionally left untranslated.
Strings identical in all three languages (codes, names) are omitted.

## Interface and page text (src/i18n)

${header}
${rows.join('\n')}

## Achievements (src/data/achievements.json)

${header}
${achievementRows.join('\n')}

## Gallery alt text (src/data/gallery.json)

${header}
${galleryRows.join('\n')}
`;

writeFileSync(new URL('../TRANSLATIONS_REVIEW.md', import.meta.url), doc);
console.log(`TRANSLATIONS_REVIEW.md written (${rows.length + achievementRows.length + galleryRows.length} rows).`);
